DailyLoan/DailyLoan/Controllers/PayController.cs
using DailyLoan.Model;
using DailyLoan.Model.Entities.DailyLoan;
using DailyLoan.Model.Request.Management;
using DailyLoan.Model.Resoinse.Pay;
using DailyLoan.Library;
using DailyLoan.Library.Status;
using DailyLoan.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using static System.Net.Mime.MediaTypeNames;
using Newtonsoft.Json;

namespace DailyLoan.Controllers
{
    public class PayController : Controller
    {

        private readonly IManagementService _managementService;
        private readonly IPayService _payService;
        private IWebHostEnvironment Environment;
        public PayController(IWebHostEnvironment _environment,
            IManagementService managementService,
            IPayService payService)
        {
            Environment = _environment;
            _managementService = managementService;
            _payService = payService;
        }
        public async Task<ActionResult> AdminReportDaily()
        {
            var UserId = HttpContext.Session.GetString(ConstMessage.Session_UserId);
            var UserAccess = HttpContext.Session.GetString(ConstMessage.Session_UserAccess);
            if (String.IsNullOrEmpty(UserId) || UserId == "0") return RedirectToAction(ConstMessage.View_Index, ConstMessage.Controller_Home);
            else
            {
                if (true) //if (Convert.ToInt32(UserAccess) <= StatusUserAccess.UserAccess_Admin)
                {
                    ViewBag.UserId = UserId;
                    ViewBag.UserAccess = UserAccess;
                    if (Convert.ToInt32(UserAccess) == StatusUserAccess.UserAccess_Superadmin)
                        ViewBag.House = await _managementService.GetAllHouse();
                    else if(Convert.ToInt32(UserAccess) == StatusUserAccess.UserAccess_Admin)
                        ViewBag.CustomerLine = await _managementService.GetAllCustomerLine(Convert.ToInt32(UserId));
                    else
                        ViewBag.CustomerLine = _payService.GetCustomerLineIdByUserId(Convert.ToInt32(UserId));
                    ViewBag.partialView = ConstMessage.View_PAY_AdminReportDaily;
                    return View(ConstMessage.View_Index);
                }
                //else return RedirectToAction(ConstMessage.View_Index, ConstMessage.Controller_Home);
            }
        }
        [HttpGet]
        [Route("GetAlert")]
        public async Task<ActionResult> GetAlert()
        {
            var UserId = HttpContext.Session.GetString(ConstMessage.Session_UserId);
            var UserAccess = HttpContext.Session.GetString(ConstMessage.Session_UserAccess);
            if (String.IsNullOrEmpty(UserId) || UserId == "0") return RedirectToAction(ConstMessage.View_Index, ConstMessage.Controller_Home);
            else
            {
                var rtn = await _payService.GetAlert(Convert.ToInt32(UserId), Convert.ToInt32(UserAccess));
                rtn.Add(Convert.ToInt32(UserAccess)==StatusUserAccess.UserAccess_Agent?0:1);
                return Ok(rtn);
            }
        }
        #region system_setting
        public async Task<ActionResult> setting_systemAsync()
        {
            var UserId = HttpContext.Session.GetString(ConstMessage.Session_UserId);
            var UserAccess = HttpContext.Session.GetString(ConstMessage.Session_UserAccess);
            if (String.IsNullOrEmpty(UserId) || UserId == "0") return RedirectToAction(ConstMessage.View_Index, ConstMessage.Controller_Home);
            else
            {
                if (Convert.ToInt32(UserAccess) == StatusUserAccess.UserAccess_Superadmin)
                {
                    ViewBag.UserId = UserId;
                    ViewBag.UserAccess = UserAccess;
                    /** /
                    if (Convert.ToInt32(UserAccess) == StatusUserAccess.UserAccess_Superadmin)
                    {
                        ViewBag.House = await _managementService.GetAllHouseList();
                    }
                    else
                    {
                        int hid = _managementService.GetHouseIdByUserId(Convert.ToInt32(UserId));
                        ViewBag.House = hid;
                        ViewBag.PageData = await _managementService.GetConfig(hid);
                    }
                    /**/
                    ViewBag.PageData = await _managementService.GetConfig(1);
                    ViewBag.partialView = ConstMessage.View_PAY_setting_system;
                    return View(ConstMessage.View_Index);
                }
                else return RedirectToAction(ConstMessage.View_Index, ConstMessage.Controller_Home);
            }
        }
        [HttpGet]
        [Route("GetConfigDetail/{hid}")]
        public async Task<ActionResult> GetConfigDetail(int hid)
        {
            var UserId = HttpContext.Session.GetString(ConstMessage.Session_UserId);
            var UserAccess = HttpContext.Session.GetString(ConstMessage.Session_UserAccess);
            if (String.IsNullOrEmpty(UserId) || UserId == "0") return RedirectToAction(ConstMessage.View_Index, ConstMessage.Controller_Home);
            else { return Ok(await _managementService.GetConfig(hid)); }
        }
        [HttpGet]
        [Route("GetSpecialRateDetail/{spid}")]
        public ActionResult GetSpecialRateDetail(int spid)
        {
            var UserId = HttpContext.Session.GetString(ConstMessage.Session_UserId);
            var UserAccess = HttpContext.Session.GetString(ConstMessage.Session_UserAccess);
            if (String.IsNullOrEmpty(UserId) || UserId == "0") return RedirectToAction(ConstMessage.View_Index, ConstMessage.Controller_Home);
            else { return Ok(_managementService.GetSpecialRate(spid)); }
        }
        [HttpGet]
        [Route("DeleteSpecialRate/{spid}")]
        public async Task<ActionResult> DeleteSpecialRate(int spid)
        {
            var UserId = HttpContext.Session.GetString(ConstMessage.Session_UserId);
            var UserAccess = HttpContext.Session.GetString(ConstMessage.Session_UserAccess);
            if (String.IsNullOrEmpty(UserId) || UserId == "0") return RedirectToAction(ConstMessage.View_Index, ConstMessage.Controller_Home);
            else { 
                if (Convert.ToInt32(UserAccess) <= StatusUserAccess.UserAccess_Admin)
                {
                    if (await _managementService.DeleteSpecialRate(spid))
                    {
                        return Ok(ConstMessage.Message_Successful);
                    }
                    else return BadRequest(ConstMessage.Message_SomethingWentWrong);
                }
                else return BadRequest(ConstMessage.Message_DonotHavePermission);
            }
        }
        [HttpPost]
        [Route("EditConfig")]
        public async Task<ActionResult> EditConfig(EditConfigRequest req)
        {
            var UserId = HttpContext.Session.GetString(ConstMessage.Session_UserId);
            var UserAccess = HttpContext.Session.GetString(ConstMessage.Session_UserAccess);
            if (String.IsNullOrEmpty(UserId) || UserId == "0") return RedirectToAction(ConstMessage.View_Index, ConstMessage.Controller_Home);
            else { 
                if (await _managementService.EditConfig(req, Convert.ToInt32(UserId)))
                {
                    return Ok(ConstMessage.Message_Successful);
                }
                else return BadRequest(ConstMessage.Message_SomethingWentWrong);
            }
        }
        [HttpPost]
        [Route("EditSpecialRate")]
        public async Task<ActionResult> EditSpecialRate(EditSpecialRateRequest req)
        {
            var UserId = HttpContext.Session.GetString(ConstMessage.Session_UserId);
            var UserAccess = HttpContext.Session.GetString(ConstMessage.Session_UserAccess);
            if (String.IsNullOrEmpty(UserId) || UserId == "0") return RedirectToAction(ConstMessage.View_Index, ConstMessage.Controller_Home);
            else { 
                if (await _managementService.EditSpecialRate(req, Convert.ToInt32(UserId)))
                {
                    return Ok(ConstMessage.Message_Successful);
                }
                else return BadRequest(ConstMessage.Message_SomethingWentWrong);
            }
        }
        #endregion
        #region system_daily
        public async Task<ActionResult> setting_daily()
        {
            var UserId = HttpContext.Session.GetString(ConstMessage.Session_UserId);
            var UserAccess = HttpContext.Session.GetString(ConstMessage.Session_UserAccess);
            if (String.IsNullOrEmpty(UserId) || UserId == "0") return RedirectToAction(ConstMessage.View_Index, ConstMessage.Controller_Home);
            else {
                if (Convert.ToInt32(UserAccess) <= StatusUserAccess.UserAccess_Admin)
                {
                    ViewBag.UserId = UserId;
                    ViewBag.UserAccess = UserAccess;
                    if (Convert.ToInt32(UserAccess) == StatusUserAccess.UserAccess_Superadmin)
                        ViewBag.House = await _managementService.GetAllHouse();
                    else
                        ViewBag.CustomerLine = await _managementService.GetAllCustomerLine(Convert.ToInt32(UserId));
                    //ViewBag.PageData = 35000;
                    ViewBag.partialView = ConstMessage.View_PAY_setting_daily;
                    return View(ConstMessage.View_Index);
                }
                else return RedirectToAction(ConstMessage.View_Index, ConstMessage.Controller_Home);
            }
        }

        [HttpPost]
        [Route("GetMustReturn")]
        public async Task<ActionResult> GetMustReturn(DailyCostSearchRequest req)
        {
            var rtn = await _payService.GetMustReturn(req.clid, req.date);
            return Ok(rtn);
        }

DailyLoan/DailyLoan/Views/Shared/_Layout.cshtml
@using DailyLoan.Library;
@using DailyLoan.Library.Status;
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ซีมันนี่</title>
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap-icons.min.css" rel="stylesheet" />
    <link href="~/lib/css/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/jquery/bootstrap-table/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/css/fileinput.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <!--<script src="~/lib/js/jquery-3.6.0.min.js" type="text/javascript"></script> -->
    <script src="~/lib/jquery/dist/jquery.min.js" type="text/javascript"></script>
    <script src="~/lib/jquery/bootstrap-table/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/lib/jquery/bootstrap-table/js/dataTables.bootstrap.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        body {
            min-height: 75rem;
        }

        .myDiv {
            background-color: #ffe0b2;
            text-align: center;
        }
    </style>
    <header>
        <div class="myDiv">
            <img src="~/lib/images/logo.png" height="80" alt="">
        </div>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        @{
                            //if (Convert.ToInt32(HttpContextAccessor.HttpContext.Session.GetString(ConstMessage.Session_UserAccess)) <= StatusUserAccess.UserAccess_Audit)
                        }

                        @if (Convert.ToInt32(HttpContextAccessor.HttpContext.Session.GetString(ConstMessage.Session_UserAccess)) <= StatusUserAccess.UserAccess_Admin)
                        {
                            <li class="nav-item">
                                <a id="userlink" class="nav-link" asp-controller="Management" asp-action="User">ผู้ใช้งาน</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a id="customerlink" class="nav-link" asp-controller="Pay" asp-action="Customer">ลูกค้า</a>
                        </li>
                        <li class="nav-item">
                            <a id="contractlink" class="nav-link" asp-controller="Pay" asp-action="Contract">
                                สัญญากู้&nbsp;&nbsp;&nbsp;
                                <span id="contractcount" class="position-absolute translate-middle badge rounded-pill bg-danger" style="display:none;">

                                </span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a id="historylink" class="nav-link" asp-controller="Pay" asp-action="History">ประวัติ</a>
                        </li>
                        @if (Convert.ToInt32(HttpContextAccessor.HttpContext.Session.GetString(ConstMessage.Session_UserAccess)) == StatusUserAccess.UserAccess_Agent)
                        {
                            <li class="nav-item">
                                <a id="collectlink" class="nav-link" asp-controller="Pay" asp-action="Collector">เก็บเงิน</a>
                            </li>
                            <li class="nav-item">
                                <a id="dailyreportlink" class="nav-link" asp-controller="Pay" asp-action="DailyReport">สรุปค่าใช้จ่ายรายวัน</a>
                            </li>
                        }
                        @if (Convert.ToInt32(HttpContextAccessor.HttpContext.Session.GetString(ConstMessage.Session_UserAccess)) <= StatusUserAccess.UserAccess_Admin)
                        {
                            <li class="nav-item dropdown">
                                <a id="settinglink" class="nav-link dropdown-toggle" href="#" id="dropdownsetting" data-bs-toggle="dropdown" aria-expanded="false">ตั้งค่า</a>
                                <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownsetting">
                                    @if (Convert.ToInt32(HttpContextAccessor.HttpContext.Session.GetString(ConstMessage.Session_UserAccess)) == StatusUserAccess.UserAccess_Superadmin)
                                    {
                                        <li><a id="settingsystemlink" class="dropdown-item" asp-controller="Pay" asp-action="setting_system">ตั้งค่าระบบ</a></li>
                                    }
                                    <li><a id="settinghomelink" class="dropdown-item" asp-controller="Pay" asp-action="setting_home">ตั้งค่าบ้าน</a></li>
                                    <li><a id="settingdailylink" class="dropdown-item" asp-controller="Pay" asp-action="setting_daily">ค่าใช้จ่ายประจำวัน</a></li>
                                    <li><a id="settingmonthlylink" class="dropdown-item" asp-controller="Pay" asp-action="setting_monthly">ค่าใช้จ่ายประจำเดือน</a></li>
                                </ul>
                            </li>
                        }
                        @if (Convert.ToInt32(HttpContextAccessor.HttpContext.Session.GetString(ConstMessage.Session_UserAccess)) != StatusUserAccess.UserAccess_Audit)
                        {
                            <li class="nav-item">
                                <a id="adminreportdailylink" class="nav-link" asp-controller="Pay" asp-action="AdminReportDaily">สรุปการจ่ายลูกค้า</a>
                            </li>
                        }
                        @if (Convert.ToInt32(HttpContextAccessor.HttpContext.Session.GetString(ConstMessage.Session_UserAccess)) <= StatusUserAccess.UserAccess_Admin)
                        {
                            <li class="nav-item">
                                <a id="monthlyreportlink" class="nav-link" asp-controller="Pay" asp-action="MonthlyReport">สรุปประจำเดือน</a>
                            </li>
                        }
                    </ul>
                    <form class="d-flex">
                        @if (Convert.ToInt32(HttpContextAccessor.HttpContext.Session.GetString(ConstMessage.Session_UserAccess)) <= StatusUserAccess.UserAccess_Audit)
                        {
                            <a class="btn btn-dark btn-sm position-relative rounded-pill" style="width:75px;" asp-controller="Pay" asp-action="Warn">
                                แจ้งเตือน
                                <span id="alertcount" class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger" style="display:none;">

                                    <!-- <span class="visually-hidden">unread messages</span> -->
                                </span>
                            </a>
                        }
                        <div class="dropdown" style="padding-left:1em;min-width:8rem;">
                            <a href="#" class="d-flex align-items-center text-black text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                                <strong>@HttpContextAccessor.HttpContext.Session.GetString(ConstMessage.Session_Username)</strong>
                            </a>
                            <ul style="min-width:8rem;" class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                                <li><a class="dropdown-item" asp-controller="Home" asp-action="LogIn">ออกจากระบบ</a></li>
                            </ul>
                        </div>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
    </footer>
    @RenderSection("Scripts", required: false)
</body>
</html>